function bind(){
 injectMapUpgrade();renderDevices();setHeaders();renderDays();renderTimeline();selectDetection(selectedDetection);
 $('#bluetoothToggle')?.addEventListener('click',e=>{e.currentTarget.classList.toggle('is-on');toast(e.currentTarget.classList.contains('is-on')?'Bluetooth activado':'Bluetooth desactivado')});
 $$('[data-action="go-bluetooth"]').forEach(e=>e.onclick=()=>showScreen('bluetooth'));$$('[data-action="go-airpods"]').forEach(e=>e.onclick=()=>showScreen('airpods'));$$('[data-action="back-home"]').forEach(e=>e.onclick=()=>toast('Ya estás en Bluetooth'));
 $$('.noise-mode').forEach(b=>b.onclick=()=>{$$('.noise-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$$('.interactive-switch').forEach(b=>b.onclick=()=>b.classList.toggle('is-on'));
 $('#findDeviceBtn')?.addEventListener('click',syncFlow);$('#disconnectBtn')?.addEventListener('click',()=>toast('AirPods desconectados'));$('#unpairBtn')?.addEventListener('click',()=>toast('Acción de demostración'));
 $('#recenterBtn')?.addEventListener('click',updateMap);$('#zoomInBtn')?.addEventListener('click',()=>{mapZoom=Math.min(20,mapZoom+1);updateMap()});$('#zoomOutBtn')?.addEventListener('click',()=>{mapZoom=Math.max(13,mapZoom-1);updateMap()});$('#layersBtn')?.addEventListener('click',()=>{mapMode=mapMode==='roadmap'?'satellite':'roadmap';updateMap();toast(mapMode==='satellite'?'Vista satélite':'Vista de mapa')});
 $('#historyToggle')?.addEventListener('click',()=>{historyOpen=!historyOpen;renderTimeline()});$('#sheetHandle')?.addEventListener('click',()=>$('#findSheet')?.classList.toggle('expanded'));
 $('#soundBtn')?.addEventListener('click',()=>toast('Sin conexión directa. Acércate a la última ubicación.',3200));$('#nearbyBtn')?.addEventListener('click',()=>{const o=$('#nearbyOverlay');o?.classList.remove('hidden');const s=$('#nearbyStatus'),x=$('#nearbyText');if(s)s.textContent='Buscando señal…';if(x)x.textContent='Muévete por la zona para intentar establecer una conexión directa.';setTimeout(()=>{if(s)s.textContent='Fuera del alcance';if(x)x.textContent='Solo hay una ubicación aproximada reciente.'},1700)});$('#closeNearby')?.addEventListener('click',()=>$('#nearbyOverlay')?.classList.add('hidden'));
 $('#directionsBtn')?.addEventListener('click',()=>openGoogle(points[selectedPoint],true));$('#moreFindBtn')?.addEventListener('click',()=>$('#demoMenu').classList.remove('hidden'));
 $('#editPointsBtn')?.addEventListener('click',()=>{$('#demoMenu').classList.add('hidden');fillEditor();$('#pointsEditor').classList.remove('hidden')});$('#openMapBtn')?.addEventListener('click',()=>openGoogle(points[selectedPoint]));$('#closeDemoMenu')?.addEventListener('click',()=>$('#demoMenu').classList.add('hidden'));$('#savePointsBtn')?.addEventListener('click',saveEditor);$('#cancelPointsBtn')?.addEventListener('click',()=>$('#pointsEditor').classList.add('hidden'));
}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn')?.classList.remove('hidden')});$('#installBtn')?.addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
bind();
if(setupImported){showScreen('find');setTimeout(()=>{toast('Ubicaciones cargadas en este dispositivo');syncFlow()},120)}else if(location.hash==='#airpods')showScreen('airpods');else if(location.hash==='#find')showScreen('find');
