function renderDevices(){const c=$('#savedDevices');if(!c)return;c.innerHTML=DEVICES.map(d=>`<button class="device-card" data-target="${d.target||''}"><span class="device-icon"><svg><use href="#i-${d.icon}"/></svg></span><span><strong>${d.name}</strong><small>Guardado</small></span><span class="device-arrow">›</span></button>`).join('');$$('.device-card',c).forEach(b=>b.onclick=()=>b.dataset.target==='airpods'?showScreen('airpods'):toast('Dispositivo guardado'))}
function setHeaders(){$$('[data-collapse-for]').forEach(h=>{const s=document.getElementById(h.dataset.collapseFor);if(!s)return;const f=()=>h.classList.toggle('scrolled',s.scrollTop>18);s.addEventListener('scroll',f,{passive:true});f()})}
function uniqueDates(){const m=new Map();DETECTIONS.forEach(d=>{if(!m.has(d.date))m.set(d.date,d)});return [...m.values()]}
function renderDays(){const c=$('#dayStrip');if(!c)return;c.innerHTML=uniqueDates().map(d=>`<button class="day-chip ${d.date===selectedDate?'active':''}" data-date="${d.date}"><strong>${d.short}</strong><small>${d.date.slice(8)} ago.</small></button>`).join('');$$('[data-date]',c).forEach(b=>b.onclick=()=>{const list=DETECTIONS.filter(d=>d.date===b.dataset.date);selectDetection(list.at(-1))})}
function renderTimeline(){const c=$('#timeline');if(!c)return;let last='';c.innerHTML=DETECTIONS.map((d,i)=>`${d.day!==last?`<div class="timeline-day">${d.day} de agosto</div>`:''}<button class="timeline-item" data-i="${i}"><span class="timeline-time">${d.time}</span><span class="timeline-track"><i></i></span><span class="timeline-info"><strong>Punto ${d.point}</strong><small>${d.note}</small></span></button>${(last=d.day)&&''}`).join('');$$('.timeline-item',c).forEach(b=>b.onclick=()=>selectDetection(DETECTIONS[Number(b.dataset.i)]));c.classList.toggle('collapsed',!historyOpen);const ch=$('#historyChevron');if(ch)ch.textContent=historyOpen?'⌃':'⌄'}
function selectDetection(d){if(!d)return;selectedDetection=d;selectedPoint=d.point;selectedDate=d.date;const p=points[selectedPoint];const title=$('#selectedPointTitle'),detail=$('#selectedPointDetail'),age=$('#locationAge'),last=$('#lastSeenText'),head=$('#findHeaderStatus');if(title)title.textContent=p.title;if(detail)detail.textContent=d.note;if(age)age.textContent=relative(d);if(last)last.textContent=`${d.day}, ${d.time} · ${p.title}`;if(head)head.textContent=d.current?'Última señal · ubicación aproximada':'Detección anterior · ubicación aproximada';renderDays();renderTimeline();updateMap()}
function showScreen(name){Object.entries(screens).forEach(([k,e])=>e&&e.classList.toggle('active',k===name));currentScreen=name;history.replaceState({screen:name},'',name==='bluetooth'?location.pathname:location.pathname+'#'+name);if(name==='find')setTimeout(updateMap,60)}
function syncFlow(){showScreen('find');const o=$('#syncOverlay'),p=$('#syncProgress'),t=$('#syncTitle'),x=$('#syncText');if(!o)return selectDetection(DETECTIONS.at(-1));o.classList.remove('hidden');p.style.width='14%';t.textContent='Sincronizando búsqueda…';x.textContent='Consultando la última ubicación disponible';setTimeout(()=>p.style.width='55%',280);setTimeout(()=>{t.textContent='Ubicación encontrada';x.textContent='Se encontró una ubicación aproximada reciente';p.style.width='100%'},760);setTimeout(()=>{o.classList.add('hidden');selectDetection(DETECTIONS.at(-1))},1280)}
function parseCoord(v){const m=(v||'').trim().match(/(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)/);return m?{lat:Number(m[1]),lng:Number(m[2])}:null}
function fillEditor(){['1','2','3'].forEach(id=>{$(`#point${id}Field`).value=`${points[id].lat},${points[id].lng}`})}
function saveEditor(){const n=clone(points);for(const id of ['1','2','3']){const p=parseCoord($(`#point${id}Field`).value);if(!p)return toast(`Coordenadas inválidas en Punto ${id}`,3000);n[id]={...n[id],...p}}points=n;savePoints();$('#pointsEditor').classList.add('hidden');selectDetection(selectedDetection);toast('Ubicaciones actualizadas')}

